force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/addrline4__c.field-meta.xml
<CustomField>
    <fullName>addrline4__c</fullName>
    <inlineHelpText>Location City, State and Zip</inlineHelpText>
    <label>Address City State Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/addrline5__c.field-meta.xml
<CustomField>
    <fullName>addrline5__c</fullName>
    <inlineHelpText>Location other information</inlineHelpText>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/addrpost_code__c.field-meta.xml
<CustomField>
    <fullName>addrpost_code__c</fullName>
    <inlineHelpText>Zip Code</inlineHelpText>
    <label>Address Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Oppdest__c.field-meta.xml
<CustomField>
    <fullName>Oppdest__c</fullName>
    <label>Oppdest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddNewProspectCtrlTest.cls
@IsTest
public class AddNewProspectCtrlTest {
    public Static TestMethod void test(){
        Account objacc = new Account(name = 'asdasda');
        Contact con = new Contact(Lastname = 'sadasda');
        
        AddNewProspectCtrl.saveRecords(con,objacc,new Account());
        
        Account acc = new Account(name = 'asdasdas');
        Location__C loc = new Location__C(addrline4__c='asdas',addrpost_code__c ='asdasd',Oppdest__c = 'asdas0',addrline5__c ='asdas');
        AddNewProspectCtrl.saveRecordsLoc(loc,acc,new Location__c());
        
    }
}