force-app/main/default/objects/BPF__c/BPF__c.object-meta.xml
<CustomObject>
    <label>BPF</label>
    <nameField>
        <displayFormat>BPF-{00000}</displayFormat>
        <label>BPF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BPF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BPF__c/fields/BPF__c.field-meta.xml
<CustomField>
    <fullName>BPF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BPF</label>
    <referenceTo>BPF__c</referenceTo>
    <relationshipLabel>BPF</relationshipLabel>
    <relationshipName>BPF</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BPF__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BPF Renewal</fullName>
            </value>
            <value>
                <fullName>BPF Trader In Process</fullName>
                <default>true</default>
                <label>BPF Trader In Process</label>
            </value>
            <value>
                <fullName>BPF Trader Completed</fullName>
            </value>
            <value>
                <fullName>BPF Customer Input WIP</fullName>
            </value>
            <value>
                <fullName>BPF Customer Input Completed</fullName>
            </value>
            <value>
                <fullName>BPF World Check In Review</fullName>
            </value>
            <value>
                <fullName>BPF World Check Passed</fullName>
            </value>
            <value>
                <fullName>Trader Approval</fullName>
            </value>
            <value>
                <fullName>BPF Signed</fullName>
            </value>
            <value>
                <fullName>BPF Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WCOProcessBatch__c/WCOProcessBatch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>WCOProcessBatch</label>
</CustomObject>

force-app/main/default/classes/WCOProcessBatchTest.cls
@IsTest(SeeAllData=true)
public Class WCOProcessBatchTest{

    public static testMethod void test1(){
        BPF__c o = [select id from BPF__c LIMIT 1 ];
        o.Stage__c = 'BPF Customer Input Completed';
        update o;
        
        UPSERT new WCOProcessBatch__c(name = o.Id) NAME;
        
        test.startTest();
            new WCOProcessBatch().execute(null);
        Test.stopTest();
    }
}