force-app/main/default/objects/BPF__c/BPF__c.object-meta.xml
<CustomObject>
    <label>BPF</label>
    <nameField>
        <displayFormat>BPF-{00000}</displayFormat>
        <label>BPF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BPF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BPF__c/fields/BPF__c.field-meta.xml
<CustomField>
    <fullName>BPF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BPF</label>
    <referenceTo>BPF__c</referenceTo>
    <relationshipLabel>BPF</relationshipLabel>
    <relationshipName>BPF</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BPF__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BPF Renewal</fullName>
            </value>
            <value>
                <fullName>BPF Trader In Process</fullName>
                <default>true</default>
                <label>BPF Trader In Process</label>
            </value>
            <value>
                <fullName>BPF Trader Completed</fullName>
            </value>
            <value>
                <fullName>BPF Customer Input WIP</fullName>
            </value>
            <value>
                <fullName>BPF Customer Input Completed</fullName>
            </value>
            <value>
                <fullName>BPF World Check In Review</fullName>
            </value>
            <value>
                <fullName>BPF World Check Passed</fullName>
            </value>
            <value>
                <fullName>Trader Approval</fullName>
            </value>
            <value>
                <fullName>BPF Signed</fullName>
            </value>
            <value>
                <fullName>BPF Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BPF__c/fields/Ultimate_Beneficial_Owner_UBO_1__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Beneficial_Owner_UBO_1__c</fullName>
    <label>Ultimate Beneficial Owner (UBO) 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BPF__c/fields/Ultimate_Beneficial_Owner_UBO_2__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Beneficial_Owner_UBO_2__c</fullName>
    <label>Ultimate Beneficial Owner (UBO) 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BPF__c/fields/Ultimate_Beneficial_Owner_UBO_3__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Beneficial_Owner_UBO_3__c</fullName>
    <label>Ultimate Beneficial Owner (UBO) 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BPF__c/fields/Ultimate_Beneficial_Owner_UBO_4__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Beneficial_Owner_UBO_4__c</fullName>
    <label>Ultimate Beneficial Owner (UBO) 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BPFTriggerTest.cls
@IsTest
public Class BPFTriggerTest{
    
    public static testMethod void test1(){
        BPF__c objBPF = new BPF__c(
            Stage__c = 'BPF Trader In Process',
            Ultimate_Beneficial_Owner_UBO_1__c = ' Tess Test 1',
            Ultimate_Beneficial_Owner_UBO_2__c = ' Tess Test 2',
            Ultimate_Beneficial_Owner_UBO_3__c = ' Tess Test 3',
            Ultimate_Beneficial_Owner_UBO_4__c = ' Tess Test 4'
        );
        INSERT objBPF;
        
        objBPF.Stage__c = 'BPF Signed';
        try{
            UPDATE objBPF;
        }catch(Exception ex){}
        
        
    }
}