force-app/main/default/objects/BPF__c/BPF__c.object-meta.xml
<CustomObject>
    <label>BPF</label>
    <nameField>
        <displayFormat>BPF-{00000}</displayFormat>
        <label>BPF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BPF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BPF__c/fields/BPF__c.field-meta.xml
<CustomField>
    <fullName>BPF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BPF</label>
    <referenceTo>BPF__c</referenceTo>
    <relationshipLabel>BPF</relationshipLabel>
    <relationshipName>BPF</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BPF__c/fields/Process_WCO__c.field-meta.xml
<CustomField>
    <fullName>Process_WCO__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Process WCO</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BPF__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BPF Renewal</fullName>
            </value>
            <value>
                <fullName>BPF Trader In Process</fullName>
                <default>true</default>
                <label>BPF Trader In Process</label>
            </value>
            <value>
                <fullName>BPF Trader Completed</fullName>
            </value>
            <value>
                <fullName>BPF Customer Input WIP</fullName>
            </value>
            <value>
                <fullName>BPF Customer Input Completed</fullName>
            </value>
            <value>
                <fullName>BPF World Check In Review</fullName>
            </value>
            <value>
                <fullName>BPF World Check Passed</fullName>
            </value>
            <value>
                <fullName>Trader Approval</fullName>
            </value>
            <value>
                <fullName>BPF Signed</fullName>
            </value>
            <value>
                <fullName>BPF Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WCOProcessBatch__c/WCOProcessBatch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>WCOProcessBatch</label>
</CustomObject>

force-app/main/default/classes/WCOProcessBatch.cls
public class WCOProcessBatch implements Database.Batchable<sObject>, Schedulable{

   public Database.QueryLocator start(Database.BatchableContext BC){
       String query = 'select name from WCOProcessBatch__c';
       if(Test.isRunningTest()){
           query = 'select name from WCOProcessBatch__c LIMIT 1';
       }
      return Database.getQueryLocator(query);
   }
    
    public void execute(SchedulableContext sc) {
        Database.executeBatch( new WCOProcessBatch(), 1 );
   }
    
   public void execute(Database.BatchableContext BC, List<WCOProcessBatch__c> scope){
        WCOProcessBatch__c o  = scope[0];
        
        try{
            BPF__c objBPF = [select id from BPF__C where id = : o.Name AND Stage__c = 'BPF Customer Input Completed' AND Process_WCO__c = false];
            objBPF.Process_WCO__c = true;
            update objBPF;
            DELETE o;
        }catch(Exception ex){
            SYstem.debug('>>>>>>>>>>>>>>ERROR---- '+ ex);
        }
    }

   public void finish(Database.BatchableContext BC){
        Long startingTime = System.now().getTime(); 
        Integer delayInMilliseconds = 1000 * 60 ; 
            while (System.now().getTime() - startingTime < delayInMilliseconds)  {
        }
       WCOProcessBatch batch = new WCOProcessBatch();
       if(!Test.isRunningTest()) Database.executeBatch( batch, 1 );
        
   }
}