force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>OPP-{00000}</displayFormat>
        <label>Opportunity</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Mobile_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ComplexQuoteLightning.cls
public class ComplexQuoteLightning {
	@AuraEnabled
    public static Opportunity__c getOpportunityObject(Id oppid) {
        Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('Opportunity__c').getDescribe().fields.getMap();
 
        String commaSepratedFields = '';
        for(String fieldName : fieldMap.keyset()){
            if(commaSepratedFields == null || commaSepratedFields == ''){
                commaSepratedFields = fieldName;
            }else{
                commaSepratedFields = commaSepratedFields + ', ' + fieldName;
            }
        }
 
        String query = 'select ' + commaSepratedFields + ',Account__r.BillingCountry  from Opportunity__c where id =:oppid ';
 		Opportunity__c op = new Opportunity__c();
        for(Opportunity__c o : Database.query(query)){
            op = o;break;
        }
        return op;
    }
}