force-app/main/default/objects/Market_Information__c/Market_Information__c.object-meta.xml
<CustomObject>
    <label>Market Information</label>
    <nameField>
        <displayFormat>MarketInfo-{00000}</displayFormat>
        <label>Market Information</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Information__c/fields/CanadaOrOtherSupply__c.field-meta.xml
<CustomField>
    <fullName>CanadaOrOtherSupply__c</fullName>
    <label>Canada (or other) Supply</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Market_Information__c/fields/Commentry__c.field-meta.xml
<CustomField>
    <fullName>Commentry__c</fullName>
    <label>Commentry</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Market_Information__c/fields/Dairy_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Dairy_Product_Type__c</fullName>
    <label>Dairy Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BMP</fullName>
            </value>
            <value>
                <fullName>Butter</fullName>
            </value>
            <value>
                <fullName>Cheese</fullName>
            </value>
            <value>
                <fullName>Fluids</fullName>
            </value>
            <value>
                <fullName>Lactose</fullName>
            </value>
            <value>
                <fullName>Lonestar</fullName>
            </value>
            <value>
                <fullName>MPC</fullName>
            </value>
            <value>
                <fullName>Nonfat-SMP</fullName>
            </value>
            <value>
                <fullName>Permeate</fullName>
            </value>
            <value>
                <fullName>Protein</fullName>
            </value>
            <value>
                <fullName>SWP</fullName>
            </value>
            <value>
                <fullName>WMP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Information__c/fields/EUSupply__c.field-meta.xml
<CustomField>
    <fullName>EUSupply__c</fullName>
    <label>EU Supply</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Market_Information__c/fields/FutureCommentry__c.field-meta.xml
<CustomField>
    <fullName>FutureCommentry__c</fullName>
    <label>Future Commentry</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Market_Information__c/fields/OceaniaSupply__c.field-meta.xml
<CustomField>
    <fullName>OceaniaSupply__c</fullName>
    <label>Oceania Supply</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Market_Information__c/fields/Pricing__c.field-meta.xml
<CustomField>
    <fullName>Pricing__c</fullName>
    <label>Pricing</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Market_Information__c/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/MarketUpdateThisWeekCtrl.cls
public class MarketUpdateThisWeekCtrl {
    
    public Date dt = System.today().toStartofWeek();
    Date dtend = dt.addDays(7);
    
    public List<Market_Information__c> lstMarket_Information {get;set;}
    
    public MarketUpdateThisWeekCtrl() {
        lstMarket_Information = [select id,CanadaOrOtherSupply__c,Commentry__c,Dairy_Product_Type__c,EUSupply__c,FutureCommentry__c,OceaniaSupply__c,Position__c,Pricing__c,Send_Date__c,Strategy__c,name from Market_Information__c where Send_Date__c >=:dt AND Send_Date__c <=: dtend ];
    }
}