force-app/main/default/objects/Market_Information__c/Market_Information__c.object-meta.xml
<CustomObject>
    <label>Market Information</label>
    <nameField>
        <displayFormat>MarketInfo-{00000}</displayFormat>
        <label>Market Information</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Information__c/fields/Dairy_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Dairy_Product_Type__c</fullName>
    <label>Dairy Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BMP</fullName>
            </value>
            <value>
                <fullName>Butter</fullName>
            </value>
            <value>
                <fullName>Cheese</fullName>
            </value>
            <value>
                <fullName>Fluids</fullName>
            </value>
            <value>
                <fullName>Lactose</fullName>
            </value>
            <value>
                <fullName>Lonestar</fullName>
            </value>
            <value>
                <fullName>MPC</fullName>
            </value>
            <value>
                <fullName>Nonfat-SMP</fullName>
            </value>
            <value>
                <fullName>Permeate</fullName>
            </value>
            <value>
                <fullName>Protein</fullName>
            </value>
            <value>
                <fullName>SWP</fullName>
            </value>
            <value>
                <fullName>WMP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Information__c/fields/Pricing__c.field-meta.xml
<CustomField>
    <fullName>Pricing__c</fullName>
    <label>Pricing</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MarketEmailServiceFields__c/MarketEmailServiceFields__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>MarketEmailServiceFields</label>
</CustomObject>

force-app/main/default/classes/BatchRunTest.cls
@IsTest
public class BatchRunTest{

    public static TestMethod void test1(){
        Market_Information__c obj = new Market_Information__c();
        obj.Dairy_Product_Type__c = 'BMP';
        obj.ownerID = UserInfo.getUserId();
        insert obj;
        
        MarketEmailServiceFields__c o = new MarketEmailServiceFields__c ();
        o.name = 'Pricing__c';
        o.label__C = 'Pricing';
        insert o;
        
        BatchRun obj1 = new BatchRun();
        obj1.redirect();
    }
}