force-app/main/default/objects/Approval__c/Approval__c.object-meta.xml
<CustomObject>
    <label>Approval</label>
    <nameField>
        <displayFormat>Appval-{00000}</displayFormat>
        <label>Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval__c/fields/After_held_Approved_from__c.field-meta.xml
<CustomField>
    <fullName>After_held_Approved_from__c</fullName>
    <label>After held_Approved from</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Approval__c/fields/After_held_Audit_result_approved__c.field-meta.xml
<CustomField>
    <fullName>After_held_Audit_result_approved__c</fullName>
    <label>After held_Audit result approved</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval__c/fields/After_held_Feedback_on_report_arranged__c.field-meta.xml
<CustomField>
    <fullName>After_held_Feedback_on_report_arranged__c</fullName>
    <label>After held_Feedback on report arranged?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Close_this_audit_process__c.field-meta.xml
<CustomField>
    <fullName>Close_this_audit_process__c</fullName>
    <label>Close this audit process?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Customer_Qmanual_available_and_known_by__c.field-meta.xml
<CustomField>
    <fullName>Customer_Qmanual_available_and_known_by__c</fullName>
    <label>Customer Qmanual available and known by</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Customer_specification_available__c.field-meta.xml
<CustomField>
    <fullName>Customer_specification_available__c</fullName>
    <label>Customer specification available</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Documents_to_prepare_send_prior_to_audit__c.field-meta.xml
<CustomField>
    <fullName>Documents_to_prepare_send_prior_to_audit__c</fullName>
    <label>Documents to prepare/send prior to audit</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Name_of_the_auditor__c.field-meta.xml
<CustomField>
    <fullName>Name_of_the_auditor__c</fullName>
    <label>Name of the auditor</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origin</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Characteristic__c.Characteristic_Key__c</field>
            <operation>equals</operation>
            <value>ORIGIN</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Characteristic__c</referenceTo>
    <relationshipLabel>Approval (Origin)</relationshipLabel>
    <relationshipName>Approval4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Physical_audit_or_on_remote__c.field-meta.xml
<CustomField>
    <fullName>Physical_audit_or_on_remote__c</fullName>
    <label>Physical audit or on remote?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>On remote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Pre_audit_by_Hoogwegt_required__c.field-meta.xml
<CustomField>
    <fullName>Pre_audit_by_Hoogwegt_required__c</fullName>
    <label>Pre-audit by Hoogwegt required?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Product_Factcode__c.field-meta.xml
<CustomField>
    <fullName>Product_Factcode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Factcode</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Characteristic__c.Characteristic_Key__c</field>
            <operation>equals</operation>
            <value>factcode</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Characteristic__c</referenceTo>
    <relationshipLabel>Approval (Product Factcode)</relationshipLabel>
    <relationshipName>Approval3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Reason_for_audit__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_audit__c</fullName>
    <label>Reason for audit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initial audit</fullName>
            </value>
            <value>
                <fullName>Re-approval audit</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Namely</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Starting_date_of_the_audit__c.field-meta.xml
<CustomField>
    <fullName>Starting_date_of_the_audit__c</fullName>
    <label>Starting date of the audit</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Case</fullName>
            </value>
            <value>
                <fullName>Technical Feasibility</fullName>
            </value>
            <value>
                <fullName>Final Combinations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_Combination__c/Approval_Combination__c.object-meta.xml
<CustomObject>
    <label>Approval Combination</label>
    <nameField>
        <displayFormat>AC-{00000}</displayFormat>
        <label>Approval Combination Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Combination</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Combination__c/fields/Approval__c.field-meta.xml
<CustomField>
    <fullName>Approval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval</label>
    <referenceTo>Approval__c</referenceTo>
    <relationshipLabel>Approval Combination</relationshipLabel>
    <relationshipName>Approval_Combination</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Combination__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>DeepDive</fullName>
            </value>
            <value>
                <fullName>Final Closing</fullName>
            </value>
            <value>
                <fullName>Sample Request</fullName>
            </value>
            <value>
                <fullName>Trial Shipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Origin__c/Origin__c.object-meta.xml
<CustomObject>
    <label>Origin</label>
    <nameField>
        <label>Origin</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Origins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ApprovalStatusBarclTest.cls
@IsTest
public class ApprovalStatusBarclTest{
  public static testMethod void testBar(){
    Approval__c oApproval = new Approval__c(Origin__c = 'Argentina', Product_Factcode__c = 'ALL', Physical_audit_or_on_remote__c = 'Physical', Reason_for_audit__c = 'Other',
                        Pre_audit_by_Hoogwegt_required__c = 'Yes', Documents_to_prepare_send_prior_to_audit__c = 'test', Customer_specification_available__c = 'No', Customer_Qmanual_available_and_known_by__c = 'No',
                        Name_of_the_auditor__c = 'test', Starting_date_of_the_audit__c = Date.today(), After_held_Feedback_on_report_arranged__c = 'No', After_held_Audit_result_approved__c = 'No', 
                        After_held_Approved_from__c = Date.today(), Close_this_audit_process__c = 'No');
    insert oApproval;
    Approval_Combination__c oCom = new Approval_Combination__c(Approval__c = oApproval.Id, Status__c = 'Final Closing');
    insert oCom;
    ApprovalStatusBarcl.loadStatus(oApproval.Id);
  }
}