force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Address_Line4__c.field-meta.xml
<CustomField>
    <fullName>Address_Line4__c</fullName>
    <label>Address Line4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <label>Item Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Packaging__c.field-meta.xml
<CustomField>
    <fullName>Packaging__c</fullName>
    <label>Packaging</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Select__c.field-meta.xml
<CustomField>
    <fullName>Select__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Select</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>OPP-{00000}</displayFormat>
        <label>Opportunity</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <label>Item Description</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AMF 99.9% Butterfat</fullName>
            </value>
            <value>
                <fullName>Soft Butteroil Substitute</fullName>
            </value>
            <value>
                <fullName>Standard Butteroil Substitute</fullName>
            </value>
            <value>
                <fullName>Concentrated Milk Fat</fullName>
            </value>
            <value>
                <fullName>Salted Butter-80% Fat</fullName>
            </value>
            <value>
                <fullName>UNSALTED 80 LACTIC BUTTER</fullName>
            </value>
            <value>
                <fullName>Unsalted Butter-80% Fat</fullName>
            </value>
            <value>
                <fullName>Buttermilk</fullName>
            </value>
            <value>
                <fullName>Buttermilk Ex Gr Swt Crm (&gt;30% Prtn)</fullName>
            </value>
            <value>
                <fullName>Caseinate, Calcium</fullName>
            </value>
            <value>
                <fullName>Caseinate, Sodium</fullName>
            </value>
            <value>
                <fullName>Rennet Casein</fullName>
            </value>
            <value>
                <fullName>ASIAGO</fullName>
            </value>
            <value>
                <fullName>BLUE CHEESE CRUMBLES</fullName>
            </value>
            <value>
                <fullName>BRIE (MISC)</fullName>
            </value>
            <value>
                <fullName>COLBY</fullName>
            </value>
            <value>
                <fullName>COLBY JACK</fullName>
            </value>
            <value>
                <fullName>COLORED CHEDDAR</fullName>
            </value>
            <value>
                <fullName>CREAM CHEESE</fullName>
            </value>
            <value>
                <fullName>EDAM CHEESE</fullName>
            </value>
            <value>
                <fullName>FETA</fullName>
            </value>
            <value>
                <fullName>FONTINA</fullName>
            </value>
            <value>
                <fullName>GOUDA</fullName>
            </value>
            <value>
                <fullName>HAVARTI</fullName>
            </value>
            <value>
                <fullName>MONTEREY JACK</fullName>
            </value>
            <value>
                <fullName>MOZZARELLA</fullName>
            </value>
            <value>
                <fullName>MUENSTER</fullName>
            </value>
            <value>
                <fullName>PARMESAN</fullName>
            </value>
            <value>
                <fullName>PEPPER JACK</fullName>
            </value>
            <value>
                <fullName>PIZZA CHEESE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Characteristic__c/Product_Characteristic__c.object-meta.xml
<CustomObject>
    <label>Product_Characteristic</label>
    <nameField>
        <displayFormat>ProdChr-{00000}</displayFormat>
        <label>Product_Characteristic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product_Characteristics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Characteristic__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Product_Characteristics</relationshipLabel>
    <relationshipName>Product_Characteristics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Characteristic__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Product_Characteristics</relationshipLabel>
    <relationshipName>Product_Characteristics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductPageCtrl.cls
public class ProductPageCtrl {
  
    public List<SelectOption> productName{get;set;}
    public String selectedProductName{get;set;}
    
    public List<SelectOption> vendar{get;set;}
    public String selectedVendar{get;set;}
    
    public List<SelectOption> address{get;set;}
    public String SelectedAddress{get;set;}
    
    public List<SelectOption> part{get;set;}
    public String selectedPart{get;set;}
    
    public List<SelectOption> packing{get;set;}
    public String selectedPacking{get;set;}
    
    public List<Item__c > lstResult{get;set;}
    
    public ProductPageCtrl(){
        init();
        populateData();
        lstResult = new List<Item__c>();
    }
    
    
    
    public void init(){
        productName = new List<SelectOption>();
        vendar =  new List<SelectOption>();
        address = new List<SelectOption>();
        part = new List<SelectOption>();
        part.add(new SelectOption('',''));
        packing = new List<SelectOption>();
        packing.add(new SelectOption('',''));
    }
    
    public void populateData(){
        Set<String> set1 = new Set<String>();
        Set<String> set2 = new Set<String>();
        Set<String> set3 = new Set<String>();
        Set<String> set4 = new Set<String>();
        Set<String> set5 = new Set<String>();
        
       for(Item__c obj : [select id,name,Vendor__c,Address_Line4__c,Item_Description__c,Packaging__c,Select__c,Item_Type__c from Item__c ]) {
            set1.add(obj.name);
            set2.add(obj.Vendor__c);
            set3.add(obj.Address_Line4__c);
            set4.add(obj.Item_Description__c);
            set5.add(obj.Packaging__c);
        } 
        set1.remove(null);
        set2.remove(null);
        set3.remove(null);
        set4.remove(null);
        set5.remove(null);
        
        for(String str : set1)
            productName.add(new SelectOption(str,str));
        for(String str : set2)
            vendar.add(new SelectOption(str,str));
        for(String str : set3)
            address.add(new SelectOption(str,str));
        for(String str : set4)
            part.add(new SelectOption(str,str));
        for(String str : set5)
            packing.add(new SelectOption(str,str));
        set1 = new Set<String>();
         set2 = new Set<String>();
        set3 = new Set<String>();
        set4 = new Set<String>();
        set5 = new Set<String>();
    }
    
    public void Search() {
        lstResult = new List<Item__c >();
        List<String> lstName = new List<String>();
        List<String> lstVendor = new List<String>();
        List<String> lstadd = new List<String>();
       for(String str : selectedProductName.split(','))
           lstName.add(str.remove('[').remove(']'));
        
        String query = '';
        query = 'select id,name,Product_Type__c,Vendor__c,Address_Line4__c,city__c,state__c,Zip__c,Product_Description__c,Packaging__c,Select__c from Item__c where (name IN : lstName) ';    
        
        if(selectedPart != null && selectedPart != ''){
            query += ' AND Product_Description__c =:selectedPart ';
        }
        if(selectedPacking != null && selectedPacking != ''){
            query += ' AND Packaging__c =:selectedPacking ';
        }
        query += ' LIMIT 900 ';
        Boolean ttt = (lstName[0] == 'Test Product');
        System.debug(lstName[0]+'>hfgdhgfhfgdhfdghfdgh>>' +query);
        for(Item__c obj : Database.query(query)) {
            lstResult.add(obj);
        }
        System.debug('>>>>>>>>>>>>>'+lstResult);
    }
    
    public void Search2() {
        lstResult = new List<Item__c  >();
        List<String> lstName = new List<String>();
        List<String> lstVendor = new List<String>();
        List<String> lstadd = new List<String>();
       for(String str : selectedProductName.split(','))
           lstName.add(str.remove('[').remove(']'));
            
        for(String str : selectedVendar.split(','))
            lstVendor.add(str.trim().remove('[').remove(']'));

        String query = '';
        query = 'select id,name,Vendor__c,Product_Type__c,Address_Line4__c,city__c,state__c,Zip__c,Product_Description__c,Packaging__c,Select__c from Item__c  where (name IN : lstName)  AND Vendor__c IN : lstVendor  ';    
        
        if(selectedPart != null && selectedPart != ''){
            query += ' AND Product_Description__c =:selectedPart ';
        }
        if(selectedPacking != null && selectedPacking != ''){
            query += ' AND Packaging__c =:selectedPacking ';
        }
        query += ' LIMIT 900 ';
        Boolean ttt = (lstName[0] == 'Test Product');
        System.debug(lstName[0]+'>hfgdhgfhfgdhfdghfdgh>>' +query);
        for(Item__c obj : Database.query(query)) {
            lstResult.add(obj);
        }
        System.debug('>>>>>>>>>>>>>'+lstResult);
    }
    
    public void Search3() {
        lstResult = new List<Item__c >();
        List<String> lstName = new List<String>();
        List<String> lstVendor = new List<String>();
        List<String> lstadd = new List<String>();
       for(String str : selectedProductName.split(','))
           lstName.add(str.remove('[').remove(']'));
            
        for(String str : selectedVendar.split(','))
            lstVendor.add(str.trim().remove('[').remove(']'));
            
        for(String str : SelectedAddress.split(','))
            lstadd.add(str.trim().remove('[').remove(']'));
            
        String query = '';
        query = 'select id,name,Vendor__c,Product_Type__c,Address_Line4__c,city__c,state__c,Zip__c,Product_Description__c,Packaging__c,Select__c from Item__c  where (name IN : lstName)  AND Vendor__c IN : lstVendor  AND Address_Line4__c IN : lstadd  ';    
        
        if(selectedPart != null && selectedPart != ''){
            query += ' AND Product_Description__c =:selectedPart ';
        }
        if(selectedPacking != null && selectedPacking != ''){
            query += ' AND Packaging__c =:selectedPacking ';
        }
        query += ' LIMIT 900 ';
        Boolean ttt = (lstName[0] == 'Test Product');
        System.debug(lstName[0]+'>hfgdhgfhfgdhfdghfdgh>>' +query);
        for(Item__c obj : Database.query(query)) {
            lstResult.add(obj);
        }
    }
    
    public PageReference  save() {
      String oppid =  apexpages.currentpage().getparameters().containsKey('id') ? apexpages.currentpage().getparameters().get('id') : '' ;
      List<Product_Characteristic__c> lst = new List<Product_Characteristic__c>();
      for(Item__c   o :lstResult ) {
          if(o.Select__c) {
              lst.add(new Product_Characteristic__c(Opportunity__c = oppid, Item__c = o.id) );
          }
      }
      if(lst.size() > 0) insert lst;
      PageReference acctPage = new ApexPages.StandardController(new Opportunity__c(id= oppid  )).view();
      acctPage.setRedirect(true);
      return acctPage;
    }
    

}