force-app/main/default/objects/Account/fields/LookupValue__c.field-meta.xml
<CustomField>
    <fullName>LookupValue__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LookupValue</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SFAccountCusNum__c.field-meta.xml
<CustomField>
    <fullName>SFAccountCusNum__c</fullName>
    <externalId>true</externalId>
    <label>SFAccountCusNum</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Location__c/Account_Location__c.object-meta.xml
<CustomObject>
    <label>Account Location</label>
    <nameField>
        <displayFormat>AL-{00000}</displayFormat>
        <label>Account Location</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Location__c/fields/addrline1__c.field-meta.xml
<CustomField>
    <fullName>addrline1__c</fullName>
    <formula>Location__r.addrline1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Location__c/fields/addrline5__c.field-meta.xml
<CustomField>
    <fullName>addrline5__c</fullName>
    <formula>Location__r.addrline5__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>addrline5</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SFLocationId</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Location__c/fields/SFAccountCusNum__c.field-meta.xml
<CustomField>
    <fullName>SFAccountCusNum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Location__c/recordTypes/Request.recordType-meta.xml
<RecordType>
    <fullName>Request</fullName>
    <active>true</active>
    <label>Request</label>
</RecordType>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/addrline1__c.field-meta.xml
<CustomField>
    <fullName>addrline1__c</fullName>
    <inlineHelpText>Location Name</inlineHelpText>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/addrline4__c.field-meta.xml
<CustomField>
    <fullName>addrline4__c</fullName>
    <inlineHelpText>Location City, State and Zip</inlineHelpText>
    <label>Address City State Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/addrline5__c.field-meta.xml
<CustomField>
    <fullName>addrline5__c</fullName>
    <inlineHelpText>Location other information</inlineHelpText>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/addrpost_code__c.field-meta.xml
<CustomField>
    <fullName>addrpost_code__c</fullName>
    <inlineHelpText>Zip Code</inlineHelpText>
    <label>Address Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/LookupValue__c.field-meta.xml
<CustomField>
    <fullName>LookupValue__c</fullName>
    <formula>addrline1__c &amp; &apos; , &apos; &amp; addrline4__c &amp; &apos; , &apos; &amp; addrline5__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LookupValue</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Oppdest__c.field-meta.xml
<CustomField>
    <fullName>Oppdest__c</fullName>
    <label>Oppdest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/recordTypes/Request.recordType-meta.xml
<RecordType>
    <fullName>Request</fullName>
    <active>true</active>
    <label>Request</label>
</RecordType>

force-app/main/default/classes/AddNewLocationCtrl.cls
public class AddNewLocationCtrl {
	
    @AuraEnabled
    public static String saveRecords(Location__C LOc,Account parentAccount, Location__c searchLocation  ){
        Account_Location__c objAL = new Account_Location__c();
        objAL.SFAccountCusNum__c = parentAccount.Id;
        objAL.RecordTypeId =  Schema.SObjectType.Account_Location__c.getRecordTypeInfosByName().get('Request').getRecordTypeId();
        if(searchLocation.Id == null ){
            LOc.addrline1__c = parentAccount.Name;
            LOc.Oppdest__c = LOc.addrline4__c;
            LOc.addrline4__c = LOc.addrline4__c + ', ' + LOc.addrpost_code__c ;
            LOc.Name = parentAccount.Name +',' + LOc.Oppdest__c + Loc.addrline5__c;
            loc.RecordTypeId = Schema.SObjectType.Location__c.getRecordTypeInfosByName().get('Request').getRecordTypeId();
            INSERT loc;    
            
            objAL.Location__c = loc.Id;
        } else {
            objAL.Location__c = searchLocation.Id;
        }
        INSERT objAL;
        return objAL.Id;
    }
    
    @AuraEnabled
    public static Account parentAccount(String recordId){
        return [select id,Name,LookupValue__c from Account where Id =:recordId LIMIT 1];
    }
    
}