force-app/main/default/objects/Account/fields/LookupValue__c.field-meta.xml
<CustomField>
    <fullName>LookupValue__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LookupValue</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MaxAVGDays__c.field-meta.xml
<CustomField>
    <fullName>MaxAVGDays__c</fullName>
    <formula>MAX(Avg_Days_to_Pay__c,AR_Terms__c,accmterms_days__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MaxAVGDays</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account Lookup</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Inactive Parent Account, Prospect-Parent, Parent Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Child Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SFAccountCusNum__c.field-meta.xml
<CustomField>
    <fullName>SFAccountCusNum__c</fullName>
    <externalId>true</externalId>
    <label>SFAccountCusNum</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Account_Location__c/Account_Location__c.object-meta.xml
<CustomObject>
    <label>Account Location</label>
    <nameField>
        <displayFormat>AL-{00000}</displayFormat>
        <label>Account Location</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SFLocationId</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Location__c/fields/SFAccountCusNum__c.field-meta.xml
<CustomField>
    <fullName>SFAccountCusNum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LookupValue__c.field-meta.xml
<CustomField>
    <fullName>LookupValue__c</fullName>
    <formula>FirstName &amp; &apos; &apos; &amp; LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LookupValue</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/LookupValue__c.field-meta.xml
<CustomField>
    <fullName>LookupValue__c</fullName>
    <formula>addrline1__c &amp; &apos; , &apos; &amp; addrline4__c &amp; &apos; , &apos; &amp; addrline5__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LookupValue</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/customLookUpController.cls
public class customLookUpController {
    @AuraEnabled
    public static List < sObject > fetchLookUpValues(String searchKeyWord, String ObjectName,String accountId) {
        Set<Id> setval = new Set<Id>();
        String criteria = '';
        String searchKey = searchKeyWord + '%';
        String sQuery = 'select id,name,LookupValue__c from '+ ObjectName + ' where id != null AND  (LookupValue__c LIKE: searchKey) order by createdDate ';
        List < sObject > returnList = new List < sObject > ();
        if(ObjectName == 'Account'){
            if(accountId != null && accountId == 'searchParentOnly'){
                sQuery = 'select id, Name,LookupValue__c from Account where (RecordType.name = \'Parent Account\' OR RecordType.name  = \'Prospect-Parent\') AND LookupValue__c LIKE: searchKey order by Name ASC limit 30 ';
            } else if(accountId == null || accountId == ''){
                sQuery = 'select id,name,LookupValue__c,MaxAVGDays__c from '+ ObjectName + ' where RecordType.name = \'Customer\' AND Status__c = \'A\' ';
            } else if(accountId != null && accountId.startsWith('003')){
                List<Contact> con = [select id,AccountId from contact where id=:accountId];
                accountId = con.size() > 0 ? con.get(0).AccountId : null ;
                sQuery =  'select id, Name,LookupValue__c,MaxAVGDays__c from ' +ObjectName + ' where  ( RecordType.name = \'Customer\' OR RecordType.name = \'Prospect-Child\' ) AND Parent_Account__c =: accountId AND LookupValue__c LIKE: searchKey order by createdDate DESC limit 30'; // Status__c = \'A\'
            } 
        } else if(ObjectName == 'Location__c' && accountId == 'searchLocationOnly'){
            sQuery = 'select id,name,LookupValue__c from Location__c where (LookupValue__c LIKE: searchKey) order by createdDate DESC limit 30 ';
        }
        else if( accountId != null && accountId != ''){
            set<Id> setid = new Set<Id>();
            List<Contact> con = [select id,AccountId from contact where id=:accountId];
            accountId = con.size() > 0 ? con.get(0).AccountId : null ;
            for(Account_Location__c acl : [select id,Location__c from Account_Location__c where SFAccountCusNum__c =:accountId ]){
                setid.add(acl.Location__c);
            }
            if(setid.size()>0){
                sQuery =  'select id, Name,LookupValue__c from ' +ObjectName + ' where (LookupValue__c LIKE: searchKey) AND Id IN :setid  order by createdDate DESC limit 30';
            }
        }
        List < sObject > lstOfRecords = Database.query(sQuery);
        System.debug('>>>>>>>>>>>>>>>>>lstOfRecords>>>'+lstOfRecords);
        for (sObject obj: lstOfRecords) {
            returnList.add(obj);
        }
        return returnList;
    }
}