force-app/main/default/objects/Account/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account Lookup</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Inactive Parent Account, Prospect-Parent, Parent Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Child Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SFAccountCusNum__c.field-meta.xml
<CustomField>
    <fullName>SFAccountCusNum__c</fullName>
    <externalId>true</externalId>
    <label>SFAccountCusNum</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Account_Location__c/Account_Location__c.object-meta.xml
<CustomObject>
    <label>Account Location</label>
    <nameField>
        <displayFormat>AL-{00000}</displayFormat>
        <label>Account Location</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Location__c/fields/addrline1__c.field-meta.xml
<CustomField>
    <fullName>addrline1__c</fullName>
    <formula>Location__r.addrline1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Location__c/fields/addrline5__c.field-meta.xml
<CustomField>
    <fullName>addrline5__c</fullName>
    <formula>Location__r.addrline5__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>addrline5</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SFLocationId</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Location__c/fields/SFAccountCusNum__c.field-meta.xml
<CustomField>
    <fullName>SFAccountCusNum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Location__c/recordTypes/Request.recordType-meta.xml
<RecordType>
    <fullName>Request</fullName>
    <active>true</active>
    <label>Request</label>
</RecordType>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/addrline1__c.field-meta.xml
<CustomField>
    <fullName>addrline1__c</fullName>
    <inlineHelpText>Location Name</inlineHelpText>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/addrline4__c.field-meta.xml
<CustomField>
    <fullName>addrline4__c</fullName>
    <inlineHelpText>Location City, State and Zip</inlineHelpText>
    <label>Address City State Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/addrline5__c.field-meta.xml
<CustomField>
    <fullName>addrline5__c</fullName>
    <inlineHelpText>Location other information</inlineHelpText>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/addrpost_code__c.field-meta.xml
<CustomField>
    <fullName>addrpost_code__c</fullName>
    <inlineHelpText>Zip Code</inlineHelpText>
    <label>Address Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Oppdest__c.field-meta.xml
<CustomField>
    <fullName>Oppdest__c</fullName>
    <label>Oppdest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/recordTypes/Request.recordType-meta.xml
<RecordType>
    <fullName>Request</fullName>
    <active>true</active>
    <label>Request</label>
</RecordType>

force-app/main/default/classes/AddNewProspectCtrl.cls
public class AddNewProspectCtrl {
    @AuraEnabled
    public Static String saveRecords(Contact objcon, Account objacc, Account selectedAcc){
        Integer len = 3;
        try{
            String str = string.valueof(Math.abs(Crypto.getRandomLong()));
            String randomNumber = str.substring(0, len);
            
            if(selectedAcc.Id == null){
                 Account acc = new Account(
                    Name = objacc.Name,
                    RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect-Parent').getRecordTypeId(),
                    SFAccountCusNum__c = '99999-' + randomNumber ,
                    Status__c = 'P'
                 );   
                INSERT acc;
                selectedAcc = acc;
                objacc.Parent_Account__c =acc.id ;
                objacc.ParentId = acc.id;
                objacc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect-Child').getRecordTypeId();
                INSERT objacc;
            }else {
                objacc.Parent_Account__c =selectedAcc.Id ;
                objacc.ParentId = selectedAcc.Id;
                objacc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect-Child').getRecordTypeId();
                INSERT objacc;
            }
            objcon.AccountId = objacc.Parent_Account__c;
            INSERT objcon;
        
            return selectedAcc.Id;
        }catch(Exception ex){
            return String.valueOf(ex);
        }
        
    }
    
     @AuraEnabled
    public static String saveRecordsLoc(Location__C LOc,Account parentAccount, Location__c searchLocation  ){
        Account_Location__c objAL = new Account_Location__c();
        objAL.SFAccountCusNum__c = parentAccount.Id;
        objAL.RecordTypeId =  Schema.SObjectType.Account_Location__c.getRecordTypeInfosByName().get('Request').getRecordTypeId();
        if(searchLocation.Id == null ){
            LOc.addrline1__c = parentAccount.Name;
            LOc.Oppdest__c = LOc.addrline4__c;
            LOc.addrline4__c = LOc.addrline4__c + ', ' + LOc.addrpost_code__c ;
            LOc.Name = parentAccount.Name +',' + LOc.Oppdest__c + Loc.addrline5__c;
            loc.RecordTypeId = Schema.SObjectType.Location__c.getRecordTypeInfosByName().get('Request').getRecordTypeId();
            INSERT loc;    
            
            objAL.Location__c = loc.Id;
        } else {
            objAL.Location__c = searchLocation.Id;
        }
        INSERT objAL;
        System.debug('>>>>>>>>>>>>>>>>>>>objAL>>>>'+objAL);
        return objAL.Id;
    }
}