force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval__c/Approval__c.object-meta.xml
<CustomObject>
    <label>Approval</label>
    <nameField>
        <displayFormat>Appval-{00000}</displayFormat>
        <label>Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval__c/fields/Factcode__c.field-meta.xml
<CustomField>
    <fullName>Factcode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Factcode</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Characteristic__c.Characteristic_Key__c</field>
            <operation>equals</operation>
            <value>Factcode</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Characteristic__c</referenceTo>
    <relationshipLabel>Approval (Factcode)</relationshipLabel>
    <relationshipName>Approval2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Case</fullName>
            </value>
            <value>
                <fullName>Technical Feasibility</fullName>
            </value>
            <value>
                <fullName>Final Combinations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_Combination__c/Approval_Combination__c.object-meta.xml
<CustomObject>
    <label>Approval Combination</label>
    <nameField>
        <displayFormat>AC-{00000}</displayFormat>
        <label>Approval Combination Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Combination</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Combination__c/fields/Approval__c.field-meta.xml
<CustomField>
    <fullName>Approval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval</label>
    <referenceTo>Approval__c</referenceTo>
    <relationshipLabel>Approval Combination</relationshipLabel>
    <relationshipName>Approval_Combination</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Combination__c/fields/Factcode__c.field-meta.xml
<CustomField>
    <fullName>Factcode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please select the Factcode associated with this Combination</inlineHelpText>
    <label>Factcode</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Characteristic__c.Characteristic_Key__c</field>
            <operation>equals</operation>
            <value>Factcode</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Characteristic__c</referenceTo>
    <relationshipLabel>Approval Combination</relationshipLabel>
    <relationshipName>Approval_Combination</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Combination__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>DeepDive</fullName>
            </value>
            <value>
                <fullName>Final Closing</fullName>
            </value>
            <value>
                <fullName>Sample Request</fullName>
            </value>
            <value>
                <fullName>Trial Shipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_Combination__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Approval Combination</relationshipLabel>
    <relationshipName>Approval_Combination</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Characteristic__c/Characteristic__c.object-meta.xml
<CustomObject>
    <label>Characteristic</label>
    <nameField>
        <label>Characteristic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Characteristic</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ApprovalStatusBarcl.cls
public class ApprovalStatusBarcl{
  @auraEnabled
  public static Map<String,List<WrapStatusBar>> loadStatus(String sRecId){
    List<Approval_Combination__c> lstCombination = [SELECT Supplier__c,Supplier__r.name,Factcode__r.name,Status__c FROM Approval_Combination__c WHERE Approval__c =: sRecId ORDER BY LastModifiedDate DESC ];
    Map<Integer, String> mapStatus = getPickListValuesIntoList();
      Map<String,List<WrapStatusBar>> lstStatusBar1 = new Map<String,List<WrapStatusBar>>();
    
    if(!lstCombination.isEmpty()){
        Integer iActiveStatus = 0;
        Integer i=0;
        for( Approval_Combination__c oCombination : lstCombination){
            i++;
      List<WrapStatusBar> lstStatusBar = new List<WrapStatusBar>();
      for(Integer iKey : mapStatus.keySet()){
        String sStatusValue = mapStatus.get(iKey);
        String sStatusType = 'incomplete';
        if(sStatusValue == oCombination.Status__c){
          sStatusType = 'active';
          iActiveStatus = iKey;
        }
        lstStatusBar.add(new WrapStatusBar(sStatusValue, sStatusType, iKey));
      }
            for(WrapStatusBar oBar : lstStatusBar){
        if(oBar.iStatusNumber < iActiveStatus){
          oBar.sStatusType = 'complete';
        }
        if(oBar.iStatusNumber > iActiveStatus){
          oBar.sStatusType = 'incomplete';
        }
      }
            String combo='';
            combo+=i;
            if(oCombination.Supplier__r.name!=null){combo+=oCombination.Supplier__r.name+'/';}
            if(oCombination.Factcode__r.name!=null){combo+=oCombination.Factcode__r.name;}
            //lstStatusBar1.put(oCombination.Supplier__r.name + oCombination.Factcode__r.name ,lstStatusBar);
            lstStatusBar1.put(combo,lstStatusBar);
            System.debug(' Inside Loopppppp '+oCombination.Supplier__r.name);
      }
      
    }
    return lstStatusBar1;
  }
  
  public static Map<Integer, String> getPickListValuesIntoList(){
    Schema.DescribeFieldResult fieldResult = Approval_Combination__c.Status__c.getDescribe();
    List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    Map<Integer, String> mapStatus = new Map<Integer, String>();
    Integer count = 1;
    for( Schema.PicklistEntry pickListVal : ple){
      mapStatus.put(count, pickListVal.getLabel());
      count++;
    }
    return mapStatus;
  }
  
  public class WrapStatusBar{
    @auraEnabled
    public String sStatusValue;
    @auraEnabled
    public String sStatusType;
    @auraEnabled
    public Integer iStatusNumber;
      
    
    public WrapStatusBar(String sValue, String sType, Integer iNumber){
      sStatusValue = sValue;
      sStatusType = sType;
      iStatusNumber = iNumber;
    }
  }
}