force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <label>Offer Name/ Email Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offer_Contact__c/Offer_Contact__c.object-meta.xml
<CustomObject>
    <label>Offer Contact</label>
    <nameField>
        <displayFormat>OC-{0000}</displayFormat>
        <label>Offer Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Contact</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Offer Contact</relationshipLabel>
    <relationshipName>Offer_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offer_Contact__c/fields/Offer__c.field-meta.xml
<CustomField>
    <fullName>Offer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offer</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipLabel>Offer Contact</relationshipLabel>
    <relationshipName>Offer_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offer_Contact__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OfferContatcCtrl.cls
public class OfferContatcCtrl {
	
   @AuraEnabled
    public static List <sObject> fetchLookUpValues(String searchKeyWord, String ObjectName, List<sObject> ExcludeitemsList) {
        String searchKey = '%' + searchKeyWord + '%';
        List < sObject > returnList = new List < sObject > ();
        String sQuery = '';
        if(ObjectName == 'Contact'){
            sQuery =  'select id, Name from Contact where Name LIKE: searchKey order by createdDate DESC limit 10';
        }
        System.debug(sQuery);
        List < sObject > lstOfRecords = Database.query(sQuery);
        System.debug(lstOfRecords);
        for (sObject obj: lstOfRecords) {
            returnList.add(obj);
        }
        return returnList;
    }
    
    @AuraEnabled
    public static List<Offer_Contact__c> lineItemPreset(String recordId,String count,List<Offer_Contact__c> lstData){
        if(lstData.size() > 0){
              List<Offer_Contact__c> lst = new List<Offer_Contact__c>();
              lst.AddAll(CreateRecord(lstData,recordId));
              lstData = new List<Offer_Contact__c>();
              lstData.AddAll(lst);
         	  lstData.add(new Offer_Contact__c(Offer__c =recordId,Sequence__c = String.valueOf(lstData.size()))); 
        }else {
            lstData = new List<Offer_Contact__c> ();
            Integer i = 0;
            for(Offer_Contact__c o : [select id,Offer__c,Contact__c,Contact_Name__c from Offer_Contact__c where offer__c =:recordId ]){
                o.Sequence__c  = String.valueOf(i++);
                lstData.add(o);
            }
            lstData.add(new Offer_Contact__c(Offer__c =recordId,Sequence__c = String.valueOf(lstData.size())));
            lstData.add(new Offer_Contact__c(Offer__c =recordId,Sequence__c = String.valueOf(lstData.size())));
            lstData.add(new Offer_Contact__c(Offer__c =recordId,Sequence__c = String.valueOf(lstData.size())));
            lstData.add(new Offer_Contact__c(Offer__c =recordId,Sequence__c = String.valueOf(lstData.size())));
            lstData.add(new Offer_Contact__c(Offer__c =recordId,Sequence__c = String.valueOf(lstData.size())));
        }
        return lstData;
    }
   
    @AuraEnabled
    public static List<Offer_Contact__c>  CreateRecord( List<Offer_Contact__c>  lst, String recordId){
        
        List<Offer_Contact__c> lstINSERT = new List<Offer_Contact__c>();
        for(Offer_Contact__c o: lst){
            if(o.Contact__c != null){
                lstINSERT.add(o);
            }
        }
        UPSERT lstINSERT;
        return lstINSERT;
    }
    
  @AuraEnabled
  public static List<Offer_Contact__c> removeItem(List<Offer_Contact__c> lst,String rowId){
      Offer_Contact__c  obj = lst[Integer.valueOf(rowId)];
      lst.remove(Integer.valueOf(rowId));
      if(obj.Id != null)
          	DELETE obj;
      return lst;
  }
    
}