force-app/main/default/objects/Account_Opco_Info__c/Account_Opco_Info__c.object-meta.xml
<CustomObject>
    <label>Account Opco Info</label>
    <nameField>
        <label>OpCo Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Opco Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Opco_Info__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>OpCo_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Opco_Info__c/fields/Account_Opco_Info__c.field-meta.xml
<CustomField>
    <fullName>Account_Opco_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Opco Info</label>
    <referenceTo>Account_Opco_Info__c</referenceTo>
    <relationshipLabel>Account Opco Info</relationshipLabel>
    <relationshipName>Account_Opco_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Opco_Info__c/fields/CreditHoldExempt__c.field-meta.xml
<CustomField>
    <fullName>CreditHoldExempt__c</fullName>
    <label>CreditHoldExempt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Opco_Info__c/fields/CustomerCurrencyCode_ABAmounts__c.field-meta.xml
<CustomField>
    <fullName>CustomerCurrencyCode_ABAmounts__c</fullName>
    <label>CustomerCurrencyCode-ABAmounts</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Opco_Info__c/fields/Date_LastCreditReview__c.field-meta.xml
<CustomField>
    <fullName>Date_LastCreditReview__c</fullName>
    <label>Date-LastCreditReview</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Opco_Info__c/fields/DefaultAddress__c.field-meta.xml
<CustomField>
    <fullName>DefaultAddress__c</fullName>
    <label>DefaultAddress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Opco_Info__c/fields/EntityCompany__c.field-meta.xml
<CustomField>
    <fullName>EntityCompany__c</fullName>
    <label>EntityCompany</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Opco_Info__c/fields/Ext_SFAccCusNum__c.field-meta.xml
<CustomField>
    <fullName>Ext_SFAccCusNum__c</fullName>
    <label>Ext SFAccCusNum</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Opco_Info__c/fields/FreightHandlingCode__c.field-meta.xml
<CustomField>
    <fullName>FreightHandlingCode__c</fullName>
    <label>FreightHandlingCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Opco_Info__c/fields/HoldInvoices__c.field-meta.xml
<CustomField>
    <fullName>HoldInvoices__c</fullName>
    <label>HoldInvoices</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Opco_Info__c/fields/Opco__c.field-meta.xml
<CustomField>
    <fullName>Opco__c</fullName>
    <label>Opco</label>
    <referenceTo>Opco__c</referenceTo>
    <relationshipLabel>Account Opco Info</relationshipLabel>
    <relationshipName>Account_Opco_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Opco_Info__c/fields/PaymentTermsCode__c.field-meta.xml
<CustomField>
    <fullName>PaymentTermsCode__c</fullName>
    <label>PaymentTermsCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Opco_Info__c/fields/Related_AddressNumber__c.field-meta.xml
<CustomField>
    <fullName>Related_AddressNumber__c</fullName>
    <label>Related-AddressNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opco__c/Opco__c.object-meta.xml
<CustomObject>
    <label>Opco</label>
    <nameField>
        <label>Opco Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opco</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountFinanceInfoCtrl.cls
public class AccountFinanceInfoCtrl {
    @AuraEnabled
    public Static Account_Opco_Info__c getOpcoValues(String VarId){
        String UserId = UserInfo.getUserId();
        System.debug('>>>>>>>>>>>>>'+UserId);
        System.debug('>>>>>>>>>>>>>'+VarId);
        User u = [select id,CompanyName from User where Id=:UserId ];
        System.debug('>>>>>>>>>>>>>'+u);
        Account_Opco_Info__c obj = new Account_Opco_Info__c();
        for(Account_Opco_Info__c o: [select id,CreditHoldExempt__c,CustomerCurrencyCode_ABAmounts__c,Date_LastCreditReview__c,DefaultAddress__c,EntityCompany__c,Ext_SFAccCusNum__c,
                                    FreightHandlingCode__c,HoldInvoices__c,Name,PaymentTermsCode__c,Related_AddressNumber__c from Account_Opco_Info__c where 
                                     Opco__r.Name =: u.CompanyName AND Account__c =: VarId ]){
                              obj = o;           
                                     }
        System.debug('>>>>>>>>>>>>>'+obj);
        return obj;
    }
}