force-app/main/default/objects/Credit_Insurance_Rate__c/Credit_Insurance_Rate__c.object-meta.xml
<CustomObject>
    <label>Credit Insurance Rate</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Insurance Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/addrline5__c.field-meta.xml
<CustomField>
    <fullName>addrline5__c</fullName>
    <inlineHelpText>Location other information</inlineHelpText>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>OPP-{00000}</displayFormat>
        <label>Opportunity</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/OpportunityCreateEditCtrl.cls
public class OpportunityCreateEditCtrl {
	
	@AuraEnabled
    public static Opportunity__c fetchLookUpValues(String varId) { 
        List<String> lstfields = new List<String>();
        for(Schema.SObjectField sfield  : Schema.getGlobalDescribe().get('Opportunity__c').getDescribe().fields.getMap().values() ){
            schema.describefieldresult dfield = sfield.getDescribe();
            lstfields.add(dfield.getName());
        }
        String query = 'Select ' + String.join(lstfields, ',') + ' from Opportunity__c where id=: varId ';
        List<Opportunity__c> lstopp = Database.query(query) ;
    	return lstopp.get(0);
    } 
    
    @AuraEnabled
    public static Decimal generateRate(String destId) { 
        String varLocation = '';
        Decimal rate = 0.0;
        /*for(Location__c l : [select id,addrline5__c from Location__c where id =: destId ]){
            varLocation = l.addrline5__c ;
        }*/
        for(Account acc : [select id,billingCountry from Account where id =: destId]){
        	varLocation = acc.billingCountry ;
        }
        
    	for(Credit_Insurance_Rate__c o : [select id,name,Rate__c from Credit_Insurance_Rate__c where name = :varLocation ]){
           rate = o.Rate__c ;
        }
        return rate;
    } 
}