force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>AccountId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <label>Offer Name/ Email Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Offer_Close__c.field-meta.xml
<CustomField>
    <fullName>Offer_Close__c</fullName>
    <inlineHelpText>This appears after your offer on the template and will be included on your email to customers</inlineHelpText>
    <label>Offer Close</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Offer_Introduction__c.field-meta.xml
<CustomField>
    <fullName>Offer_Introduction__c</fullName>
    <inlineHelpText>This appears before your offer on the template and will be included on your email to customers</inlineHelpText>
    <label>Offer Introduction</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/OfferLineItem__c/OfferLineItem__c.object-meta.xml
<CustomObject>
    <label>Offer Line Item</label>
    <nameField>
        <displayFormat>OLI-{0000}</displayFormat>
        <label>Offer Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Line Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OfferLineItem__c/fields/Brand_Origin__c.field-meta.xml
<CustomField>
    <fullName>Brand_Origin__c</fullName>
    <label>Brand/Origin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OfferLineItem__c/fields/For_Offer__c.field-meta.xml
<CustomField>
    <fullName>For_Offer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>For Offer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OfferLineItem__c/fields/INCO__c.field-meta.xml
<CustomField>
    <fullName>INCO__c</fullName>
    <label>INCO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OfferLineItem__c/fields/Offer__c.field-meta.xml
<CustomField>
    <fullName>Offer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offer</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipLabel>Offer Line Item</relationshipLabel>
    <relationshipName>Offer_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OfferLineItem__c/fields/Packaging_Pallets__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Pallets__c</fullName>
    <label>Packaging Pallets</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OfferLineItem__c/fields/Spec_ID__c.field-meta.xml
<CustomField>
    <fullName>Spec_ID__c</fullName>
    <label>Spec - ID#</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OfferLineItem__c/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <label>Volume</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/OfferEmailSendCtrlTest.cls
@IsTest
public class OfferEmailSendCtrlTest{
  public static testMethod void testOffer(){
    Account oAcc = new Account(Name = 'test');
    insert oAcc;
    Contact oCon = new Contact(LastName = 'test', Email = 'test@test.com', AccountId = oAcc.Id);
    insert oCon;
    Offer__c oOffer = new Offer__c(Account__c = oAcc.Id, Contact__c = oCon.Id, Offer_Introduction__c = 'test', Offer_Close__c = 'test');
    insert oOffer;
    OfferLineItem__c oItem = new OfferLineItem__c(Offer__c = oOffer.Id, Brand_Origin__c = 'test', Destination__c = 'test', For_Offer__c = true, INCO__c = 'test',
                             Packaging_Pallets__c = 'test', Period__c = 'test', Price__c = 'test', Product__c = 'test', Remark__c = 'test', Sequence__c = 'test',
                             Spec_ID__c = 'test', Volume__c = 'test');
    insert oItem;
    ApexPages.currentPage().getParameters().put('Id', oOffer.Id);
    ApexPages.StandardController oStdCtrl = new ApexPages.StandardController(oOffer);
    OfferEmailSendCtrl oCtrl = new OfferEmailSendCtrl(oStdCtrl);
    oCtrl.oFile = new Attachment(Name = 'test.pdf', Body = Blob.valueOf('My Test'));
    oCtrl.addAttachment();
    oCtrl.prepareEmailAttachment();
    oCtrl.sContentDocumentId = oCtrl.lstWrapperFiles[0].sId;
    oCtrl.removeFile();
    oCtrl.sendEmail();
  }
}