force-app/main/default/objects/Request_Processors__c/Request_Processors__c.object-meta.xml
<CustomObject>
    <label>Request Processor</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Request Processors</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request_Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_Processors__c/fields/RequestProcessor__c.field-meta.xml
<CustomField>
    <fullName>RequestProcessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request Processor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Request_Processors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request_Processors__c/fields/Sample_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Sample_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sample Transaction</label>
    <referenceTo>Sample_Transaction__c</referenceTo>
    <relationshipLabel>Request_Processors</relationshipLabel>
    <relationshipName>Request_Processors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Transaction__c/Sample_Transaction__c.object-meta.xml
<CustomObject>
    <label>Sample Requests</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Request Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SampleTransactionCtrl.cls
public class SampleTransactionCtrl {
	@AuraEnabled
    public static List <User> fetchLookUpValues(String searchKeyWord,List<User> ExcludeitemsList) {
        String searchKey = '%' + searchKeyWord + '%';
        List <User> returnList = new List <User> ();
 
        List<string> lstExcludeitems = new List<string>();
        for(User item : ExcludeitemsList ){
            lstExcludeitems.add(item.id);
        }
       
        String sQuery =  'select id, Name from User where Name LIKE: searchKey AND ISActive = true AND Id NOT IN : lstExcludeitems order by createdDate DESC limit 5';
        List <User> lstOfRecords = Database.query(sQuery);
        
        for (User obj:lstOfRecords) {
            returnList.add(obj);
        }
        return returnList;
    }
    
    @AuraEnabled
    public static String insertRelatedListRecords(String varId, List<User> lstData) {
        List<Request_Processors__c> lst  = new List<Request_Processors__c>();
        for(User u : lstData){
            lst.add(new Request_Processors__c(RequestProcessor__c = u.Id , Sample_Transaction__c = varId));
        }
        INSERT lst;
        return 'success';
    }
}