force-app/main/default/objects/Account_Approval_Deep__c/Account_Approval_Deep__c.object-meta.xml
<CustomObject>
    <label>Account Approval Deep</label>
    <nameField>
        <label>Account Approval Deep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account_Approval_Deeps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Approval_Deep__c/fields/Approval__c.field-meta.xml
<CustomField>
    <fullName>Approval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval</label>
    <referenceTo>Approval__c</referenceTo>
    <relationshipLabel>Account_Approval_Deeps</relationshipLabel>
    <relationshipName>Account_Approval_Deeps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Approval_Deep__c/fields/GFSI_Certificate__c.field-meta.xml
<CustomField>
    <fullName>GFSI_Certificate__c</fullName>
    <label>GFSI Certificate</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IFS</fullName>
            </value>
            <value>
                <fullName>FSSC22000</fullName>
            </value>
            <value>
                <fullName>SQF</fullName>
            </value>
            <value>
                <fullName>Any</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Approval_Deep__c/fields/GFSI_Certificate_Required__c.field-meta.xml
<CustomField>
    <fullName>GFSI_Certificate_Required__c</fullName>
    <label>GFSI Certificate Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval__c/Approval__c.object-meta.xml
<CustomObject>
    <label>Approval</label>
    <nameField>
        <displayFormat>Appval-{00000}</displayFormat>
        <label>Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountApprovalDeep.cls
public class AccountApprovalDeep {
    @AuraEnabled
    public static Account_Approval_Deep__c getAccApproval(String ApprovalId){
        Account_Approval_Deep__c aad=[SELECT Id,GFSI_Certificate_Required__c,GFSI_Certificate__c from Account_Approval_Deep__c where Approval__c=:ApprovalId LIMIT 1];
        return aad;
    }
    @AuraEnabled
    public static void updateRecord(Account_Approval_Deep__c accAppData){
        System.debug('Inside update');
        Update accAppData;
        System.debug('Update complete');
    }
}