force-app/main/default/objects/Copy_Opportunity__mdt/Copy_Opportunity__mdt.object-meta.xml
<CustomObject>
    <label>Copy Opportunity</label>
    <pluralLabel>Copy Opportunity</pluralLabel>
</CustomObject>

force-app/main/default/objects/Copy_Opportunity__mdt/fields/Field_API__c.field-meta.xml
<CustomField>
    <fullName>Field_API__c</fullName>
    <label>Field API</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Copy_Opportunity__mdt/fields/Instruction__c.field-meta.xml
<CustomField>
    <fullName>Instruction__c</fullName>
    <label>Instruction</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>OPP-{00000}</displayFormat>
        <label>Opportunity</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AGRIMARK</fullName>
            </value>
            <value>
                <fullName>AGROCOMERICA</fullName>
            </value>
            <value>
                <fullName>AGROPUR</fullName>
            </value>
            <value>
                <fullName>ALIMENTA</fullName>
            </value>
            <value>
                <fullName>AMPI</fullName>
            </value>
            <value>
                <fullName>APPROVED BRANDS</fullName>
            </value>
            <value>
                <fullName>ARLA</fullName>
            </value>
            <value>
                <fullName>BELGIOIOSO</fullName>
            </value>
            <value>
                <fullName>BINCO</fullName>
            </value>
            <value>
                <fullName>BLUEGRASS</fullName>
            </value>
            <value>
                <fullName>BONGARDS</fullName>
            </value>
            <value>
                <fullName>BORDEN</fullName>
            </value>
            <value>
                <fullName>BREWSTER</fullName>
            </value>
            <value>
                <fullName>BRIESS</fullName>
            </value>
            <value>
                <fullName>CAYUGA MILK</fullName>
            </value>
            <value>
                <fullName>CDC</fullName>
            </value>
            <value>
                <fullName>CDI</fullName>
            </value>
            <value>
                <fullName>CEDAR VALLEY</fullName>
            </value>
            <value>
                <fullName>CHALLENGE</fullName>
            </value>
            <value>
                <fullName>CLALDY</fullName>
            </value>
            <value>
                <fullName>COLUN</fullName>
            </value>
            <value>
                <fullName>CONAPROLE</fullName>
            </value>
            <value>
                <fullName>CONTINENTAL</fullName>
            </value>
            <value>
                <fullName>COOPERATIVA</fullName>
            </value>
            <value>
                <fullName>CORLASA</fullName>
            </value>
            <value>
                <fullName>CROPP</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>DAITANVET</fullName>
            </value>
            <value>
                <fullName>DANONE</fullName>
            </value>
            <value>
                <fullName>DARIGOLD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Destination_CopyPast__c.field-meta.xml
<CustomField>
    <fullName>Destination_CopyPast__c</fullName>
    <formula>Destination_Location__r.Oppdest__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Destination_CopyPast</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Destination_Location__c.field-meta.xml
<CustomField>
    <fullName>Destination_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Opportunities (Destination)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Inco_Terms__c.field-meta.xml
<CustomField>
    <fullName>Inco_Terms__c</fullName>
    <label>Inco Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3RD</fullName>
                <label>3rd</label>
            </value>
            <value>
                <fullName>CFR</fullName>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>CPU</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>DPU</fullName>
            </value>
            <value>
                <fullName>DDP</fullName>
            </value>
            <value>
                <fullName>DEL</fullName>
            </value>
            <value>
                <fullName>EXW</fullName>
            </value>
            <value>
                <fullName>FAS</fullName>
            </value>
            <value>
                <fullName>FCA</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
            <value>
                <fullName>FRC</fullName>
            </value>
            <value>
                <fullName>PFD</fullName>
            </value>
            <value>
                <fullName>PPA</fullName>
            </value>
            <value>
                <fullName>T/T</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Origin_formula__c.field-meta.xml
<CustomField>
    <fullName>Origin_formula__c</fullName>
    <formula>Origin__r.Copypaste_Data__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Origin_formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>1. Open - This is a new opportunity the trader is working on with the customer.

2. Closed/Dead - This is an opportunity the customer has declined.

3. Sold -This is an opportunity the customer has approved for sale. When changed to sold, the opportunity should go to the commercial assistant (CA) dashboard. There may need to be warnings if it stays in the “Sold” stage for too long.

4. In Process - This is when the opportunity has been picked up by a CA and they are working on entering it into the ERP system.

5. Entered - This is when the opportunity has been entered into the ERP system.</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>WIP</fullName>
                <default>true</default>
                <label>WIP</label>
            </value>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Entered</fullName>
            </value>
            <value>
                <fullName>Closed/Dead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityExt.cls
public class OpportunityExt {
    public String data{get;set;}
    Id oppid = null;
    String query = 'SELECT ';
    Opportunity__c objOpp ;
    Copy_Opportunity__mdt objCopyOpp;
    List<String> lstAPIs = new List<String>(); 
    Map<String,String> mapAPIType = new Map<String,String>();
    List<String> args = new String[]{'0','number','###,###,##0.00'};
    
    public OpportunityExt(ApexPages.StandardController controller) {
        test();
        oppid = controller.getId();
        objOpp = [select id,Inco_Terms__c from Opportunity__c where id=:oppid ];
        System.debug('>>>>>>>>>>>>>>>>'+objOpp.Inco_Terms__c);
    }
    
    public void init(){
        try {
            getFieldMap();
            getFieldsAPI();
            getRecordData();
            updateDATAvalues();
            OpportunityExt.myFutureMethod(oppid);
        }catch(Exception ex){
            data = 'No content Found';
        }
    }
    
    void getFieldMap(){
        Map <String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('Opportunity__c').getDescribe().fields.getMap();
        for(Schema.SObjectField sfield : fieldMap.Values() ){
            schema.describefieldresult dfield = sfield.getDescribe();
            mapAPIType.put(dfield.getName().toLowerCase(), String.valueof(dfield.getType()) );
        }
    }
    
    void getFieldsAPI(){
        objCopyOpp = [select id,MasterLabel,DeveloperName,Field_API__c,Instruction__c from  Copy_Opportunity__mdt where MasterLabel = :objOpp.Inco_Terms__c  ];
        for(String apis :objCopyOpp.Field_API__c.split(',') ){
            query = query + apis +', ';
            lstAPIs.add(apis);
        }
        query = query + ' id,Destination_Location__c  from Opportunity__c where id =\''+oppid + '\'';
    }
    
    void getRecordData(){
        if(Database.query(query).size() > 0)
            objOpp =(Opportunity__c) Database.query(query).get(0);
        else {
            objOpp = new Opportunity__c();
        }
    }
    
    void updateDATAvalues(){
        
        data = objCopyOpp.Instruction__c ;
        for(String objAPI :lstAPIs ){
            if(data.containsIgnoreCase(objAPI)){
            	if(mapAPIType.get(objAPI.toLowerCase()) == 'DOUBLE'){
                    data = data.replace( objAPI,' ' +  objOpp.get(objAPI) != null ? String.format(Decimal.valueOf(String.valueOf(objOpp.get(objAPI))).format(), args ) : '' );    
                } else if(mapAPIType.get(objAPI.toLowerCase()) == 'PICKLIST') {
                    data = data.replace( objAPI,' ' +  String.valueOf( objOpp.get(objAPI) != null ? objOpp.get(objAPI) : '' ) + ' ' );    
                } else if(mapAPIType.get(objAPI.toLowerCase()) == 'MULTIPICKLIST') {
                    data = data.replace( objAPI,' ' +  String.valueOf( objOpp.get(objAPI) != null ? objOpp.get(objAPI) : '' ) + ' ' );  
                    if(objOpp.Brand__c == null || objOpp.Brand__c == ''  ){
                    	data = data.replace( '["at sellers option"]', '' );
                    } else if(objOpp.Brand__c.split(';').size() < 2 ){
                    	data = data.replace( '["at sellers option"]', '' );
                    }
                } else if(mapAPIType.get(objAPI.toLowerCase()) == 'STRING') {
                    data = data.replace( objAPI,' ' +  String.valueOf( objOpp.get(objAPI) != null ? objOpp.get(objAPI) : '' ) + ' ' );    
                } else if(mapAPIType.get(objAPI.toLowerCase()) == 'STRING') {
                    data = data.replace( objAPI,' ' +  String.valueOf( objOpp.get(objAPI) != null ? objOpp.get(objAPI) : '' ) + ' ' );    
                }else if(mapAPIType.get(objAPI.toLowerCase()) == 'CURRENCY'){
                    data = data.replace( objAPI, objOpp.get(objAPI) != null ? ' $' + String.format(Decimal.valueOf(String.valueOf(objOpp.get(objAPI))).format(), args ) : '' );    
                }else if(mapAPIType.get(objAPI.toLowerCase()) == 'DATE'){
                    data = data.replace( objAPI,' ' + ( objOpp.get(objAPI) != null ? formatDate ( (Date)objOpp.get(objAPI) ) : '' ) + ' ' );    
                }
            }
        }
        if(data.containsIgnoreCase('[Origin or Destination]')){
        	if(objOpp.Destination_Location__c != null ){
        		data = data.replace('[Origin or Destination]' ,' ' + objOpp.Destination_CopyPast__c );
        	} else if(objOpp.Origin_formula__c != null ){
        		data = data.replace( '[Origin or Destination]',' ' + objOpp.Origin_formula__c );
        	}
        	
        }
        
        
    }
    
    public static String formatDate(Date d) {
        return d.month() + '/' + d.Day() + '/' + d.year();
    }
    
    @future
    public static void myFutureMethod(String ids){
        Opportunity__c objOpp = new Opportunity__c(id= ids);   
        objOpp.Stage__c = 'Quoted';
        update objOpp;
   }
    
    public void test(){
        string str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        str = 'str';
        
    
    }
}